Improve handling of resolved yet stuck method calls
njit-jerse/specimin pull request #301
Opened 2024-06-07 13:47 UTC by kelloggm

Makes the input in #298 compilable. The test case I've added on checks for part of the problem, but I verified the actual problem is fixed, too.

2024-06-07 13:48 UTC, kelloggm commented on src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
> +    String methodName = method.getNameAsString();
This change is unrelated, but it makes life simpler for the nullness checker

2024-06-09 16:59 UTC, LoiNguyenCS requested changes
Professor, I have a few questions regarding this PR.

2024-06-10 20:59 UTC, kelloggm commented on src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java
> +          if (scopeAsString.equals("this") || scopeAsString.equals("super")) {
It should be the FQN of either the superclass or an implemented interface, I think. TargetMethodFinderVisitor doesn't actually track that information, though, and without a test case for this situation I'm disinclined to add another data structure to keep track of it. I'll add a comment to the code here with a TODO, instead, and open an issue.

2024-06-11 01:26 UTC, LoiNguyenCS approved these changes
LGTM.

2024-06-11 01:26 UTC, merged